# This is a basic workflow to help you get started with Actions

name: Airflow/DAG

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  airflow:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7' 

    - uses: actions/setup-java@v1
      with:
        java-version: '9.0.4' 

    - name: Run pip install
      run: |
        pip install -r requirements.txt
        
    - name: Configure Airflow
      run: |
        export AIRFLOW_HOME=${{ GITHUB.workspace }}
        airflow upgradedb
        airflow variables -s ENVIRONMENT TEST
        airflow list_dags

    - name: Run DAG tests
      run: |
        export AIRFLOW_HOME=${{ GITHUB.workspace }}
        export ENVIRONMENT=TEST
        airflow test github_poll_trigger check_commits_hello_world 2020-03-28
